[project]
name = "mlx_driver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
    "flex>=6.14.1",
    "hf-xet>=1.1.8",
    "jinja2>=3.1.6",
    "mlx-lm>=0.28.3",
    "torch>=2.9.0",
]
